version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: nginx -g "daemon off";
    depends_on:      
      - mongodb
      - nodejs

  mongodb:
    container_name: mongodb
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=seanwasere
      
  nodejs:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    expose:
      - "8080"
    command: npm start

